baseURL      = "https://a7.andremoreno.com/"

languageCode  = "en-us"

title        = "Through the lens of A7 x VSCO"

# disableHugoGeneratorInject = false

disableKinds = ["section", "taxonomy", "term"]



[params]
description = "Through the lens of A7 x VSCO"
    [params.gallerydeluxe]
        # Shuffle the images in the gallery to give the impression of a new gallery each page load.
        shuffle = false

        # Reverse the order of the images in the gallery.
        reverse = true

        # Enable Exif data in the gallery.
        # See https://gohugo.io/content-management/image-processing/#exif-data for how to filter tags.
        enable_exif = true

[caches]
    [caches.images]
        dir    = ':resourceDir/_gen'
        maxAge =  -1

[imaging]
    resampleFilter = "Lanczos"
    quality        = 75
    anchor         = "smart"
    [imaging.exif]
        disableDate    = true
        disableLatLong = true
        includeFields  = 'Make$|Model|LensModel|FocalLength$|FNumber|ExposureTime|ImageDescription'

[server]
    [[server.headers]]
        for = '/**'
        [server.headers.values]
            Referrer-Policy = 'strict-origin-when-cross-origin'

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source = "static"
        target = "static"
    [[module.mounts]]
        source = 'content/images'
        target = 'content/images'
    [[module.imports]]
        path = "github.com/andremoreno/gallerydeluxe"