[build]
  publish = "public"
  command = "hugo --gc --minify"

[dev]
  framework = "hugo"
  command = "hugo server --disableFastRender --gc --minify"

[deploy]
  command = "netlify deploy --prod --dir=public"


[context.production.environment]
  HUGO_VERSION = "0.104.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"